src/Entity/AppUsers.php
<?php

namespace App\Entity;

use App\Repository\AppUsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AppUsersRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class AppUsers implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="vul gebruikersnaam in")
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     *
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=60)
     * @Assert\Email(
     *    message = "The email '{{ value }}' is geen geldig email adres")
     * @Assert\NotBlank(message="vul emailadres in")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\NotBlank(message="vul voorletters in")
     */
    private $voorletters;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $tussenvoegsel;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\NotBlank(message="vul achternaam in")
     */
    private $achternaam;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\NotBlank(message="vul adres in")
     */
    private $adres;

    /**
     * @ORM\Column(type="string", length=7)
     * @Assert\NotBlank(message="vul postcode in")
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank(message="vul woonplaats in")
     */
    private $woonplaats;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\NotBlank(message="vul telfoonnummer in")
     */
    private $telefoon;

    /**
     * @ORM\ManyToMany(targetEntity=Activiteiten::class, inversedBy="users")
     */
    private $activiteiten;

    public function __construct()
    {
        $this->activiteiten = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getVoorletters(): ?string
    {
        return $this->voorletters;
    }

    public function setVoorletters(string $voorletters): self
    {
        $this->voorletters = $voorletters;

        return $this;
    }

    public function getTussenvoegsel(): ?string
    {
        return $this->tussenvoegsel;
    }

    public function setTussenvoegsel(?string $tussenvoegsel): self
    {
        $this->tussenvoegsel = $tussenvoegsel;

        return $this;
    }

    public function getAchternaam(): ?string
    {
        return $this->achternaam;
    }

    public function setAchternaam(string $achternaam): self
    {
        $this->achternaam = $achternaam;

        return $this;
    }

    function getNaam()
    {
        return $this->voorletters . " " . $this->tussenvoegsel . " " . $this->achternaam;
    }

    public function getAdres(): ?string
    {
        return $this->adres;
    }

    public function setAdres(string $adres): self
    {
        $this->adres = $adres;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getWoonplaats(): ?string
    {
        return $this->woonplaats;
    }

    public function setWoonplaats(string $woonplaats): self
    {
        $this->woonplaats = $woonplaats;

        return $this;
    }

    public function getTelefoon(): ?string
    {
        return $this->telefoon;
    }

    public function setTelefoon(string $telefoon): self
    {
        $this->telefoon = $telefoon;

        return $this;
    }

    /**
     * @return Collection|Activiteiten[]
     */
    public function getActiviteiten(): Collection
    {
        return $this->activiteiten;
    }

    public function addActiviteiten(Activiteiten $activiteiten): self
    {
        if (!$this->activiteiten->contains($activiteiten)) {
            $this->activiteiten[] = $activiteiten;
        }

        return $this;
    }

    public function removeActiviteiten(Activiteiten $activiteiten): self
    {
        $this->activiteiten->removeElement($activiteiten);

        return $this;
    }
}

src/Controller/DeelnemerController.php
<?php

namespace App\Controller;

use App\Entity\Activiteiten;
use App\Form\UserType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


/**
 * Class DeelnemerController
 * @package App\Controller
 * @IsGranted("ROLE_USER")
 */
class DeelnemerController extends AbstractController
{
    /**
     * @Route("/user/activiteiten", name="activiteiten")
     */
    public function activiteitenAction()
    {
        $usr = $this->getUser();

        $beschikbareActiviteiten = $this->getDoctrine()
            ->getRepository(Activiteiten::class)
            ->getBeschikbareActiviteiten($usr->getId());

        $ingeschrevenActiviteiten = $this->getDoctrine()
            ->getRepository(Activiteiten::class)
            ->getIngeschrevenActiviteiten($usr->getId());

        $totaal = $this->getDoctrine()
            ->getRepository(Activiteiten::class)
            ->getTotaal($ingeschrevenActiviteiten);


        return $this->render('deelnemer/activiteiten.html.twig', [
            'beschikbare_activiteiten' => $beschikbareActiviteiten,
            'ingeschreven_activiteiten' => $ingeschrevenActiviteiten,
            'totaal' => $totaal,
        ]);
    }

    /**
     * @Route("/user/inschrijven/{id}", name="inschrijven")
     */
    public function inschrijvenActiviteitAction($id)
    {

        $activiteit = $this->getDoctrine()
            ->getRepository(Activiteiten::class)
            ->find($id);
        $usr = $this->get('security.token_storage')->getToken()->getUser();
        $usr->addActiviteiten($activiteit);

        $em = $this->getDoctrine()->getManager();
        $em->persist($usr);
        $em->flush();

        return $this->redirectToRoute('activiteiten');
    }

    /**
     * @Route("/user/uitschrijven/{id}", name="uitschrijven")
     */
    public function uitschrijvenActiviteitAction($id)
    {
        $activiteit = $this->getDoctrine()
            ->getRepository(Activiteiten::class)
            ->find($id);
        $usr = $this->get('security.token_storage')->getToken()->getUser();
        $usr->removeActiviteiten($activiteit);
        $em = $this->getDoctrine()->getManager();
        $em->persist($usr);
        $em->flush();
        return $this->redirectToRoute('activiteiten');
    }

    /**
     * @Route("/user/gegevens", name="show_user_gegevens")
     */
    public function showGegevens()
    {
        return $this->render('deelnemer/gegevens.html.twig');
    }

    /**
     * @Route("/user/edit/{password}", name="edit_user")
     * @param Request $request
     * @param UserPasswordEncoderInterface $encoder
     * @param EntityManagerInterface $em
     * @param $password
     */
    public function UserEdit(Request $request, UserPasswordEncoderInterface $encoder, EntityManagerInterface $em, $password)
    {
        $title = "";
        $user = $this->getUser();
        if ($password === "true") {
            $form = $this->createFormBuilder()
                ->add('currentPassword', PasswordType::class, [
                    'help' => 'vul uw huidig wachtwoord in',
                    'label' => 'huidig wachtwoord'])
                ->add('password', RepeatedType::class, [
                    'type' => PasswordType::class,
                    'first_options' => ['label' => 'wachtwoord'],
                    'second_options' => ['label' => 'herhaal wachtwoord'],
                ])
                ->getForm();
            $title = "Wachtwoord wijzigen";
        } else {
            $form = $this->createForm(UserType::class, $user);
            $form->remove('password');
            $title = "Gegevens wijzigen";
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($encoder->isPasswordValid($user, $form->get('currentPassword')->getData())) {

                if ($password === "true") {
                    $user->setPassword($encoder->encodePassword($user, $form->get('password')->getData()));
                } else {
                    $user = $form->getData();
                }
                $em->persist($user);
                $em->flush();

                $this->addFlash(
                    'notice',
                    'Uw gegevens zijn gewijzigd!'
                );

                return $this->redirectToRoute("show_user_gegevens");
            } else {
                $this->addFlash('error', 'Wachtwoord incorrect');
            }
        }

        return $this->render('deelnemer/wijzig.html.twig', [
            'title' => $title,
            'form' => $form->createView()
        ]);
    }
}

templates/deelnemer/activiteiten.html.twig
{% extends 'deelnemer.html.twig' %}
{% block menu %}
    <li class="active"><a href="{{ path('activiteiten') }}">home</a></li>
    <li><a href="{{ path('show_user_gegevens') }}">gegevens</a></li>
{% endblock %}


{% block content %}
    <section>
        <table class="table" style="table-layout: fixed">
            <caption>
                Dit zijn alle beschikbare activiteiten
            </caption>
            <thead>
            <tr>
                <td>datum</td>
                <td>tijd</td>
                <td>soort activiteit</td>
                <td>prijs</td>
                <td>schrijf in</td>
            </tr>
            </thead>
            <tbody>
            {% for activiteit in beschikbare_activiteiten %}
                <tr class="{% if activiteit.users|length >= activiteit.maxDeelnemers %} bg-danger {% endif %}">
                    <td>
                        {{ activiteit.datum|date("d-m-Y") }}
                    </td>
                    <td>
                        {{ activiteit.tijd|date("H:i") }}
                    </td>

                    <td>
                        {{ activiteit.soort.naam }}
                    </td>
                    <td>
                        &euro;{{ activiteit.soort.prijs|number_format(2,',','.') }}
                    </td>
                    <td title="schrijf in voor activiteit">
                        {% if activiteit.users|length >= activiteit.maxDeelnemers %}
                            vol
                        {% else %}

                            <a href="{{ path('inschrijven', {'id':activiteit.id}) }}">
                                <span class="glyphicon glyphicon-plus" style="color:red"></span>
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <table class="table" style="table-layout: fixed">
            <caption>
                Dit zijn de door jou ingeschreven activiteiten
            </caption>
            <thead>
            <tr>
                <td>datum</td>
                <td>tijd</td>
                <td>soort activiteit</td>
                <td>prijs</td>
                <td>schrijf uit</td>
            </tr>
            </thead>
            <tbody>
            {% for activiteit in ingeschreven_activiteiten %}
                <tr>
                    <td>
                        {{ activiteit.datum|date("d-m-Y") }}
                    </td>
                    <td>
                        {{ activiteit.tijd|date("H:i") }}
                    </td>

                    <td>
                        {{ activiteit.soort.naam }}
                    </td>
                    <td>
                        &euro;{{ activiteit.soort.prijs|number_format(2,',','.') }}
                    </td>
                    <td title="schrijf in voor activiteit">
                        <a href="{{ path('uitschrijven', {'id':activiteit.id}) }}">
                            <span class="glyphicon glyphicon-minus" style="color:red"></span>
                        </a>
                    </td>

                </tr>
            {% endfor %}
            <tr>
                <td>
                </td>
                <td>
                </td>
                <td>
                    Totaal prijs:
                </td>
                <td>
                    &euro;{{ totaal|number_format(2,',','.') }}

                </td>
                <td>
                </td>
            </tr>

            </tbody>
        </table>
    </section>


{% endblock %}

templates/deelnemer/gegevens.html.twig
{% extends 'deelnemer.html.twig' %}
{% set user = app.user %}
{% block menu %}
    <li><a href="{{ path('activiteiten') }}">home</a></li>
    <li class="active"><a href="{{ path('show_user_gegevens') }}">gegevens</a></li>
{% endblock %}

{% block content %}
    <h3>uw gegevens</h3>

    <button type="button" class="btn btn-secondary" onclick="location.href='{{ path('edit_user', {'password':"false"}) }}'">Gegevens wijzigen</button>
    <button type="button" class="btn btn-secondary" onclick="location.href='{{ path('edit_user', {'password':"true"}) }}'">Wachtwoord wijzigen</button>

    <br>
    <br>
    <table class="table table-striped" style="table-layout: fixed">
        <tr>
            <th>naam</th>
            <td>{{ user.naam }}</td>
        </tr>
        <tr>
            <th>gebruikersnaam</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>adres</th>
            <td> {{ user.adres }}</td>
        </tr>
        <tr>
            <th>postcode</th>
            <td> {{ user.postcode }}
        </tr>
        <tr>
            <th>woonplaats</th></td>
            <td>{{ user.woonplaats }}</td>
        </tr>
        <tr>
            <th>email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>telefoon</th>
            <td>{{ user.telefoon }}</td>
        </tr>
    </table>
{% endblock %}

templates/deelnemer/wijzig.html.twig
{% extends 'deelnemer.html.twig' %}

{% block menu %}
    <li><a href="{{ path('activiteiten') }}">home</a></li>
    <li><a href="{{ path('show_user_gegevens') }}">gegevens</a></li>
{% endblock %}

{% block content %}
    <h3> {{ title }}</h3>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-primary">Opslaan</button>
    {{ form_end(form) }}
{% endblock %}